import type { ManagedApp } from "./types";

export const seedApps: ManagedApp[] = [
  {
    id: "crafty-controller",
    name: "Crafty Controller",
    description: "Minecraft server management",
    category: "Gaming",
    url: "http://localhost:8443",
    icon: "https://cdn.simpleicons.org/minecraft/65E6A5",
    color: "#65e6a5",
    status: "unknown",
    source: "manual",
    isFavorite: true,
    isVisible: true,
    sortOrder: 0,
  },
  {
    id: "cloud-drive",
    name: "Cloud Drive",
    description: "Private files, anywhere",
    category: "Productivity",
    url: "http://localhost:8080",
    icon: "https://cdn.simpleicons.org/nextcloud/8BE9FD",
    color: "#8be9fd",
    status: "unknown",
    source: "manual",
    isFavorite: true,
    isVisible: true,
    sortOrder: 1,
  },
  {
    id: "immich",
    name: "Immich",
    description: "Personal photo library",
    category: "Media",
    url: "http://localhost:2283",
    icon: "https://cdn.simpleicons.org/immich",
    color: "#ffb86b",
    status: "unknown",
    source: "manual",
    isFavorite: false,
    isVisible: true,
    sortOrder: 2,
  },
  {
    id: "jellyfin",
    name: "Jellyfin",
    description: "Your media, your way",
    category: "Media",
    url: "http://localhost:8096",
    icon: "https://cdn.simpleicons.org/jellyfin/b08cff",
    color: "#b08cff",
    status: "unknown",
    source: "manual",
    isFavorite: false,
    isVisible: true,
    sortOrder: 3,
  },
  {
    id: "adguard-home",
    name: "AdGuard Home",
    description: "Network-wide privacy",
    category: "Infrastructure",
    url: "http://localhost:3001",
    icon: "https://cdn.simpleicons.org/adguard/65e6a5",
    color: "#65e6a5",
    status: "unknown",
    source: "manual",
    isFavorite: false,
    isVisible: true,
    sortOrder: 4,
  },
  {
    id: "uptime-kuma",
    name: "Uptime Kuma",
    description: "Service monitoring",
    category: "Infrastructure",
    url: "http://localhost:3002",
    icon: "https://cdn.simpleicons.org/uptimekuma/65e6a5",
    color: "#65e6a5",
    status: "unknown",
    source: "manual",
    isFavorite: false,
    isVisible: true,
    sortOrder: 5,
  },
  {
    id: "paperless",
    name: "Paperless-ngx",
    description: "A home for your documents",
    category: "Productivity",
    url: "http://localhost:8000",
    icon: "https://cdn.simpleicons.org/paperlessngx/ffb86b",
    color: "#ffb86b",
    status: "unknown",
    source: "manual",
    isFavorite: false,
    isVisible: true,
    sortOrder: 6,
  },
  {
    id: "router",
    name: "Router admin",
    description: "Network controls",
    category: "Infrastructure",
    url: "http://192.168.1.1",
    icon: "https://cdn.simpleicons.org/openwrt/8be9fd",
    color: "#8be9fd",
    status: "unknown",
    source: "manual",
    isFavorite: false,
    isVisible: true,
    sortOrder: 7,
  },
];
